import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/utils/providers.dart';
import '../../../core/utils/nickname_generator.dart';
import '../../../core/utils/country_locale.dart';
import '../../../data/models/player_profile.dart';
import '../../../data/repositories/player_profile_repository.dart';
import '../../league/widgets/league_tier_badge.dart' show kActiveTiers;

final playerProfileRepositoryProvider = Provider<PlayerProfileRepository>((ref) {
  return PlayerProfileRepository(ref.watch(sharedPrefsProvider));
});

class PlayerProfileNotifier extends Notifier<PlayerProfile> {
  @override
  PlayerProfile build() {
    final existing = ref.read(playerProfileRepositoryProvider).load();
    if (existing != null) return existing;
    return PlayerProfile(countryCode: guessCountryCodeFromLocale() ?? 'US');
  }

  Future<void> setNickname(String nickname) async {
    final trimmed = nickname.trim();
    if (trimmed.isEmpty) return;
    state = state.copyWith(nickname: trimmed, nicknameIsAutoGenerated: false);
    await _persist();
  }

  Future<void> setCountryCode(String isoCode) async {
    state = state.copyWith(countryCode: isoCode);
    await _persist();
  }

  /// Called when profile setup finishes, whether the user filled it in or
  /// hit Skip. A skip never blocks play — it just fills in a generated
  /// nickname if one wasn't chosen.
  Future<void> markSetupComplete() async {
    var next = state;
    if (next.nickname == null || next.nickname!.trim().isEmpty) {
      next = next.copyWith(nickname: generateFallbackNickname(), nicknameIsAutoGenerated: true);
    }
    next = next.copyWith(hasCompletedProfileSetup: true);
    state = next;
    await _persist();
  }

  /// Records the tier last seen from Firestore, and reports whether this
  /// is a genuine promotion since the previously recorded tier (never
  /// true on the very first call — no prior tier means nothing to compare
  /// against yet).
  Future<bool> noteTierAndCheckPromotion(String tier) async {
    const order = kActiveTiers;
    final previous = state.lastKnownTier;
    state = state.copyWith(lastKnownTier: tier);
    await _persist();
    if (previous == null) return false;
    return order.indexOf(tier) > order.indexOf(previous);
  }

  Future<void> _persist() async {
    await ref.read(playerProfileRepositoryProvider).save(state);
  }
}

final playerProfileProvider =
    NotifierProvider<PlayerProfileNotifier, PlayerProfile>(PlayerProfileNotifier.new);
