import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/utils/providers.dart';
import '../../../core/utils/nickname_generator.dart';
import '../../../core/utils/country_locale.dart';
import '../../../data/models/player_profile.dart';
import '../../../data/repositories/player_profile_repository.dart';

final playerProfileRepositoryProvider = Provider<PlayerProfileRepository>((ref) {
  return PlayerProfileRepository(ref.watch(sharedPrefsProvider));
});

class PlayerProfileNotifier extends Notifier<PlayerProfile> {
  @override
  PlayerProfile build() {
    final existing = ref.read(playerProfileRepositoryProvider).load();
    if (existing != null) return existing;
    return PlayerProfile(countryCode: guessCountryCodeFromLocale() ?? 'US');
  }

  Future<void> setNickname(String nickname) async {
    final trimmed = nickname.trim();
    if (trimmed.isEmpty) return;
    state = state.copyWith(nickname: trimmed, nicknameIsAutoGenerated: false);
    await _persist();
  }

  Future<void> setCountryCode(String isoCode) async {
    state = state.copyWith(countryCode: isoCode);
    await _persist();
  }

  /// Called when profile setup finishes, whether the user filled it in or
  /// hit Skip. A skip never blocks play — it just fills in a generated
  /// nickname if one wasn't chosen.
  Future<void> markSetupComplete() async {
    var next = state;
    if (next.nickname == null || next.nickname!.trim().isEmpty) {
      next = next.copyWith(nickname: generateFallbackNickname(), nicknameIsAutoGenerated: true);
    }
    next = next.copyWith(hasCompletedProfileSetup: true);
    state = next;
    await _persist();
  }

  /// Reports whether [weekResultId] (a players/{uid}/weekHistory doc id,
  /// e.g. "2026-W36") hasn't been shown to the player yet, and records it
  /// as shown either way. Unlike a tier comparison, this fires the first
  /// time it's ever called too — a first-ever weekHistory doc is a real
  /// result worth revealing, not a false-positive baseline the way "no
  /// prior tier" would be for a promotion check.
  Future<bool> shouldShowWeekResult(String? weekResultId) async {
    if (weekResultId == null || weekResultId == state.lastShownWeekResultId) return false;
    state = state.copyWith(lastShownWeekResultId: weekResultId);
    await _persist();
    return true;
  }

  /// Records the World Champion count last seen from Firestore, and
  /// reports whether it just went up since the previously recorded count
  /// (never true on the very first call — no prior count means nothing
  /// to compare against yet, same convention as noteTierAndCheckPromotion).
  Future<bool> noteWorldChampionCountAndCheckNewWin(int count) async {
    final previous = state.lastKnownWorldChampionCount;
    state = state.copyWith(lastKnownWorldChampionCount: count);
    await _persist();
    if (previous == null) return false;
    return count > previous;
  }

  Future<void> _persist() async {
    await ref.read(playerProfileRepositoryProvider).save(state);
  }
}

final playerProfileProvider =
    NotifierProvider<PlayerProfileNotifier, PlayerProfile>(PlayerProfileNotifier.new);
