class PlayerProfile {
  final String? nickname;
  final bool nicknameIsAutoGenerated;
  final String countryCode; // ISO 3166-1 alpha-2, e.g. "GB"
  final bool hasCompletedProfileSetup;
  final String? lastKnownTier; // for detecting a promotion since last launch
  final int? lastKnownWorldChampionCount; // for detecting a new title since last launch

  const PlayerProfile({
    this.nickname,
    this.nicknameIsAutoGenerated = false,
    this.countryCode = 'US',
    this.hasCompletedProfileSetup = false,
    this.lastKnownTier,
    this.lastKnownWorldChampionCount,
  });

  PlayerProfile copyWith({
    String? nickname,
    bool? nicknameIsAutoGenerated,
    String? countryCode,
    bool? hasCompletedProfileSetup,
    String? lastKnownTier,
    int? lastKnownWorldChampionCount,
  }) =>
      PlayerProfile(
        nickname: nickname ?? this.nickname,
        nicknameIsAutoGenerated: nicknameIsAutoGenerated ?? this.nicknameIsAutoGenerated,
        countryCode: countryCode ?? this.countryCode,
        hasCompletedProfileSetup: hasCompletedProfileSetup ?? this.hasCompletedProfileSetup,
        lastKnownTier: lastKnownTier ?? this.lastKnownTier,
        lastKnownWorldChampionCount: lastKnownWorldChampionCount ?? this.lastKnownWorldChampionCount,
      );

  Map<String, dynamic> toJson() => {
        'nickname': nickname,
        'nicknameIsAutoGenerated': nicknameIsAutoGenerated,
        'countryCode': countryCode,
        'hasCompletedProfileSetup': hasCompletedProfileSetup,
        'lastKnownTier': lastKnownTier,
        'lastKnownWorldChampionCount': lastKnownWorldChampionCount,
      };

  factory PlayerProfile.fromJson(Map<String, dynamic> json) => PlayerProfile(
        nickname: json['nickname'] as String?,
        nicknameIsAutoGenerated: json['nicknameIsAutoGenerated'] as bool? ?? false,
        countryCode: json['countryCode'] as String? ?? 'US',
        hasCompletedProfileSetup: json['hasCompletedProfileSetup'] as bool? ?? false,
        lastKnownTier: json['lastKnownTier'] as String?,
        lastKnownWorldChampionCount: json['lastKnownWorldChampionCount'] as int?,
      );
}
